### ISSUE TITLE
How to setup Solplanet on actual Home Assistant

### ISSUE THREAD

**Issue by Lafferfr** [Autista/homeassistant-solplanet#3]
Hello, 

I found your contribution. I setup the files and folders on my installation and it seems to connect to my Solplanet Device and get also Parameters from there, see screenshot. But it does not seem to create the sensors in my Home Assistant Instance. Do you have also new information, in which parameter the battery etc are in?

![image](https://github.com/user-attachments/assets/7d4e4ed2-9b9d-4d6f-87ce-4118d0b121b9)

**Comment by Lafferfr** [comment]
Many thanks for the contribution!

**Comment by matus-markusek** [comment]
Hello, 
I think you could use new HACS integration from @zbigniewmotyka
https://github.com/zbigniewmotyka/home-assistant-solplanet

In pull request there is also battery support.

**Comment by zbigniewmotyka** [comment]
Hi, thanks for sharing the link to my integration. In PR, there is added support for battery, but sadly, I don't have anyone to test it 😕 my battery will be installed next month, so I need someone to test this feature. Right now, there are only a few sensors (screen), but there will be more of them.

![Screenshot_20241010_202644_Home Assistant.jpg](https://github.com/user-attachments/assets/6acaf754-a97b-4a06-81c2-2817e585aa10)

If you want to test this integration with battery support, then on hacs installation screen, select the v0.2.0-beta1 version.

![Screenshot_20241010_202914_Home Assistant.jpg](https://github.com/user-attachments/assets/9f2d222b-269d-42c2-981b-3691c00c5597)

**Comment by Lafferfr** [comment]
Hello, I installed the Integration. I do not see the battery support, I have 6 HB-AI-G2 Batteries in place. I could test, if you provide some help here.

**Comment by Lafferfr** [comment]
I cannot find the section, where Battery information is provided.

**Comment by Lafferfr** [comment]
Sorry, I installed the 0.2.0-beta release and now there is battery support. Thank you.

**Comment by zbigniewmotyka** [comment]
I think the better place for discussion about battery support will be my PR, so I will let you know about changes in comments in PR.
